title: Project
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type: textarea
  tracks:
    label: Tracks
    type: structure
    style: table
    modalsize: large
    fields:
      title:
        label: Title
        type: text
        required: true
        width: 1/2
      file:
        label: File
        type: select
        options: files
        required: true
        width: 1/2